name: reward_transfer
channels:
  - conda-forge
dependencies:
  - python>=3.11.6

  # framework
  # choose tf version
  # - tensorflow>=2.13.1
  - tensorflow-cpu>=2.13.1
  - tensorflow-probability>=0.21.0

  # meltingpot deps
  - absl-py>=2.0.0
  - chex>=0.1.84
  - dm-env>=1.6
  - immutabledict>=3.0.0
  - ml-collections>=0.1.1
  - networkx>=3.2.1
  - numpy>=1.26.0
  - pygame>=2.5.2
  - reactivex>=4.0.4

  # reward_transfer deps
  - pandas>=2.1.2
  - ray-rllib>=2.8.1

  # optionals
  - jupyterlab

  # dev packages
  - autoflake
  - epc
  - isort
  - pandas-stubs
  - ptvsd>=4.2
  - pylsp-mypy
  - python-lsp-server  # included by pylsp-mypy

  - pip>=23.3.1
  - pip:
    - dmlab2d==1.0.0

    # dev packages
    - importmagic
    # - pylsp-rope  # leave out for now
