name: meltingpot_pip
channels:
  - conda-forge
dependencies:
  - python>=3.10

  # framework
  - tensorflow>=2.11.1
  - tensorflow-probability

  # meltingpot deps
  - absl-py
  - chex
  - dm-env
  - immutabledict
  - ml-collections
  - networkx
  - numpy==1.24.3
  - pygame
  - reactivex

  # chex deps not handled correctly my conda atm
  # compare https://github.com/deepmind/chex/blob/master/requirements/requirements.txt
  # to $ conda search chex --channel conda-forge --info
  # - jax>=0.4.6  # chex requires jax, but has a broken dependency
  # this is causing conflicts because it requires a later version fo jaxlib

  # reward_transfer deps
  - pandas
  - ray-rllib>=2.6.1

  # optionals
  - jupyterlab

  # dev packages
  - autoflake
  - epc
  - isort
  - pandas-stubs
  - ptvsd>=4.2
  - pylsp-mypy
  - python-lsp-server  # included by pylsp-mypy

  - pip>=23.1.2
  - pip:
    - dmlab2d==1.0.0

    # dev packages
    - importmagic
    # - pylsp-rope  # leave out for now
