name: mp_tf_2_14
channels:
  - conda-forge
dependencies:
  - python  # ==3.11.6  # installing the same as the module load version

  # framework
  ## if tf:
  - tensorflow-gpu==2.14.0  # compatible with cuda=11.8
  ## else if torch
  # - pytorch>=2.0.0
  # - torchvision>=0.15.2
  ## done

  ## if gpu:
  # - cudnn==8.7.0.84  # installing the same as the module load version
  # - cudnn==8.8.0.121  # installing because conda-forge does not have the above version
  # - cudatoolkit  # ==11.8.0  # installing the same as the module load version  # Cannot be later than the cuda API the GPU drivers are compatible with (run nvidia-smi)
  - gputil
  ## done

  # meltingpot deps
  - absl-py>=2.1.0
  - chex>=0.1.86
  - dm-env>=1.6
  - dm-tree>=0.1.8
  - immutabledict>=4.2.0
  - ml-collections>=0.1.1
  - networkx>=3.2.1
  - numpy>=1.26.4
  - opencv  # only needed for evaluation?
  - pandas>=2.2.2
  - pygame>=2.6.0
  - reactivex>=4.0.4

  # reward_transfer deps
  - ray-rllib==2.8.1  # 2.9.0 has a bug, so this is the latest that works with tf-2.14
  - optuna
  - wandb
  # - pandas

  - pip
  - pip:
    - dmlab2d==1.0.0
