name: meltingpot
channels:
  - conda-forge
dependencies:
  - python>=3.10.8

  # framework
  - tensorflow>=2.10.0
  - tensorflow-probability>=0.19.0

  # meltingpot deps
  - absl-py>=2.0.0
  - chex>=0.1.81
  - dm-env>=1.6
  - immutabledict>=3.0.0
  - ml-collections>=0.1.1
  - networkx>=3.1
  - numpy>=1.26.0
  - pygame>=2.2.0
  - reactivex>=4.0.4

  # chex deps not handled correctly my conda atm
  # compare https://github.com/deepmind/chex/blob/master/requirements/requirements.txt
  # to $ conda search chex --channel conda-forge --info
  # - jax>=0.4.6  # chex requires jax, but has a broken dependency
  # this is causing conflicts because it requires a later version fo jaxlib

  # reward_transfer deps
  - pandas>=2.1.1
  - ray-rllib>=2.4.0

  # optionals
  - jupyterlab

  # - pip>=23.1.2
  # - pip:
    # hack to fix jax versions
    # - jax>=0.4.7
    # - jaxlib>=0.4.6

  # install dmlab2d with install script
  # bash install-dmlab2d.sh
