name: paper_2
channels:
  - conda-forge
dependencies:
  - python  # ==3.11.6  # installing the same as the module load version

  # framework
  ## if tf:
  - tensorflow  # ==2.14.0  # installing the same as the module load version
  ## else if torch
  # - pytorch>=2.0.0
  # - torchvision>=0.15.2
  ## done

  ## if gpu:
  # - cudnn==8.7.0.84  # installing the same as the module load version
  # - cudnn==8.8.0.121  # installing because conda-forge does not have the above version
  # - cudatoolkit  # ==11.8.0  # installing the same as the module load version  # Cannot be later than the cuda API the GPU drivers are compatible with (run nvidia-smi)
  - gputil
  ## done

  # meltingpot deps
  - absl-py
  - chex
  - dm-env
  - dm-tree
  - immutabledict
  - ml-collections
  - networkx
  - numpy
  - opencv  # only needed for evaluation?
  - pandas
  - pygame
  - reactivex

  # reward_transfer deps
  - ray-rllib==2.10.0  # ==2.8.1  # or 2.9.0, this is the latest that works with the tensorflow version available
  - optuna
  - wandb
  # - pandas

  - pip
  - pip:
    - dmlab2d==1.0.0
