name: meltingpot
channels:
  - conda-forge
dependencies:
  - python>=3.11.6

  # framework
  - tensorflow>=2.13.1
  - tensorflow-probability>=0.21.0

  # meltingpot deps
  - absl-py>=2.0.0
  - chex>=0.1.84
  - dm-env>=1.6
  - immutabledict>=3.0.0
  - ml-collections>=0.1.1
  - networkx>=3.2.1
  - numpy>=1.26.0
  - pygame>=2.5.2
  - reactivex>=4.0.4

  # chex deps not handled correctly my conda atm
  # compare https://github.com/deepmind/chex/blob/master/requirements/requirements.txt
  # to $ conda search chex --channel conda-forge --info
  # - jax>=0.4.6  # chex requires jax, but has a broken dependency
  # this is causing conflicts because it requires a later version fo jaxlib

  # reward_transfer deps
  - pandas>=2.1.2
  - ray-rllib>=2.7.1

  # optionals
  - jupyterlab

  # dev packages
  - autoflake
  - epc
  - isort
  - pandas-stubs
  - ptvsd>=4.2
  - pylsp-mypy
  - python-lsp-server  # though included by pylsp-mypy

  - pip>=23.3.1
  - pip:

    # dev packages
    - importmagic
    # - pylsp-rope  # leave out for now
