name: paper_2
channels:
  - conda-forge
dependencies:
  - python

  # framework
  ## if tf:
  - tensorflow
  ## else if torch
  # - pytorch>=2.0.0
  # - torchvision>=0.15.2
  ## done

  ## if gpu:
  # - cudnn  # not installing as already on the system
  # - cudatoolkit<=12.0  # not installing as already on the system  # Cannot be later than the cuda API the GPU drivers are compatible with (run nvidia-smi)
  - gputil
  ## done

  # meltingpot deps
  - absl-py
  - chex
  - dm-env
  - dm-tree
  - immutabledict
  - ml-collections
  - networkx
  - numpy
  - opencv
  - pandas
  - pygame
  - reactivex

  # reward_transfer deps
  - ray-rllib==2.10.0
  - optuna
  # - pandas

  - pip
  - pip:
    - dmlab2d==1.0.0
