name: mp_tf_2_14
channels:
  - conda-forge
dependencies:
  - python

  - tensorflow-cpu==2.14.0

  # meltingpot deps
  - absl-py
  - chex
  - dm-env
  - dm-tree
  - immutabledict
  - ml-collections
  - networkx
  - numpy
  - opencv
  - pandas
  - pygame
  - reactivex

  # reward_transfer deps
  - ray-rllib==2.8.1
  - optuna
  # - pandas

  # optionals
  - jupyterlab
  - matplotlib

  # dev packages
  - autoflake
  - epc
  - pandas-stubs
  - ptvsd

  # lsp deps
  - pylsp-mypy
  # included by pylsp-mypy:
    # - isort
    # - python-lsp-server

  - pip
  - pip:
    - dmlab2d==1.0.0

    # dev packages
    - importmagic>=0.1.7
    - ipywidgets
    # - pylsp-rope  # leave out for now
